# Generated by Django 5.2.4 on 2025-08-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_avaliacao_options_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='deliveries.entregador'),
        ),
    ]
