# Generated by Django 5.2.4 on 2025-08-25 14:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('deliveries', '0004_alter_pedido_entregador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='cliente_nome',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='produto',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('entregador', 'Entregador'), ('pedido', 'Pedido'), ('cliente', 'Cliente'), ('servico', 'Serviço Geral'), ('estabelecimento', 'Estabelecimento')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(help_text='Nota de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['content_type', 'object_id'], name='deliveries__content_b87790_idx'),
        ),
    ]
